# Generated by Django 3.2 on 2023-08-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_titles_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genres',
            name='description',
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(),
        ),
    ]
